// -----------------------------------------------------------------------------
// Derived from the PlayerBots system in Klein187/uo-offline (GPL-3.0).
// This file is licensed under the GNU General Public License, version 3.
// See LICENSE-BOTS at the repository root.
// -----------------------------------------------------------------------------
//
// BotDoorCheck.cs - the contract test for the pathfinder door gate. Reports as Nav.Doors.
//
// WHAT IT GUARDS. Scripts/Custom/MODIFICATIONS.md entry 6: two hunks in
// Scripts/Services/Pathing/FastAStarAlgorithm.cs that let a bot's route be PLANNED through a
// closed door, which a BaseCreature has always had and a PlayerMobile never did. An upstream edit
// is the one kind of change that vanishes silently - a merge takes their file, the build stays
// green, every probe stays green, and the only symptom is a walk-failure rate nobody is watching
// that week. So it gets an assertion that fails loudly.
//
// BOTH HALVES ASSERT, and the second one is the point. A route for a real PlayerBot must succeed
// AND contain the door's tile. The same route for a plain accountless PlayerMobile must fail, or
// succeed without the door tile. The first half catches a REVERTED patch. The second catches an
// OVER-WIDENED one - somebody "simplifying" the gate to every PlayerMobile, which would hand real
// players a route through doors they have to open by hand.
//
// AND A THIRD, because the two halves of the door fix have to meet: with the route in hand, the
// bot's first step onto the door tile must open it and land. That is PlayerBot.Move going through
// Core/DoorHelper.cs, and it is what makes the planned route walkable rather than merely planned.
//
// THE SUBJECT IS A REAL PlayerBot, not a stand-in. The chain this guards is
// PlayerBot -> IBotActor -> BotPathPolicy.IgnoreDoors -> the engine gate -> the route, and a
// probe implementing IBotActor would prove every link except the first - which is precisely the
// link the class swap of 12 September 2026 broke. Bots.Death spawns real bots inside a check for
// the same reason.
//
// WHICH IS WHY IT IS CACHED AND NOT LIVE. HealthCheck.RunAll() runs every sixty seconds from
// HealthSnapshot, and constructing a PlayerBot rolls a unique name, a personality, an outfit of
// six to twenty items and a deferred mount. Once a boot is right; once a minute, for ever, is
// not. So this follows Bots.Shove and Bots.Death: the work runs from a driver and the registered
// check reports the last result. It runs at ServerStarted so every boot has a fresh answer without
// anybody typing anything, and again from [BotSmoke.
//
// THE DOOR IS REAL AND IS FOUND, NOT HARD-CODED. A door placed in open ground is routed around by
// both subjects, so the first half would fail for the right reason and the second pass for the
// wrong one; the assertion only means something in a doorway where the door tile is the only way
// through. But Britain's shop doors are generated by [DoorGen from map statics rather than shipped
// in Data/Decoration - there is not one door record in the whole decoration set inside the tailor's
// block - so there is no authored coordinate to cite. The anchors below are waypoint and arrival
// tiles read from navigation.json, and the check finds the door between them.
//
// WHY THIS FILE IS IN Bots/ AND THE CHECK IS CALLED Nav.Doors. It has to name PlayerBot, and
// Core/Navigation is not allowed to know bots exist (the rule Core/DoorHelper.cs's header states).
// Putting it there would also cost Nav.Actor's ledger a new entry. The NAME stays Nav.Doors
// because what it asserts is a navigation contract and it reads beside Nav.Movement, Nav.Data and
// Nav.Actor in the [CoreSmoke health block.

using System;
using System.Collections.Generic;

using Server.Items;
using Server.Mobiles;

using CalcMoves = Server.Movement.Movement;
using MoveImpl = Server.Movement.MovementImpl;

namespace Server.Custom
{
    public static class BotDoorCheck
    {
        private static readonly CustomLogger Log = CustomLogger.For("Bots");

        private static HealthResult _last;

        /// <summary>
        /// An outside stand tile and an inside tile with a door between them, from the edges the
        /// door regression actually failed on: the Britain tailor first, the inn as a fallback.
        ///
        /// Every coordinate is read from Data/Custom/navigation.json as shipped - the street
        /// waypoint and one of the destination's own arrival points - rather than invented, so a
        /// graph edit that moves them is visible as this check going Warn rather than as a silent
        /// drift into some other doorway.
        ///
        /// At least three tiles apart on purpose: MovementPath returns an empty path without
        /// calling Find at all when start and goal are within one (MovementPath.cs:33).
        /// </summary>
        private sealed class Anchor
        {
            public readonly string Name;
            public readonly Point3D Outside;
            public readonly Point3D Inside;

            public Anchor(string name, Point3D outside, Point3D inside)
            {
                Name = name;
                Outside = outside;
                Inside = inside;
            }
        }

        private static readonly Anchor[] Anchors =
        {
            // brit-tail-1 -> brit-shop-tailor arrival. Named in the regression ledger as one of
            // the three worst edges.
            new Anchor(
                "brit-tail-1 -> brit-shop-tailor",
                new Point3D(1467, 1686, 0),
                new Point3D(1470, 1686, 0)),

            // brit-inn-1 -> brit-inn arrival. Also named.
            new Anchor(
                "brit-inn-1 -> brit-inn",
                new Point3D(1458, 1528, 20),
                new Point3D(1467, 1523, 20))
        };

        /// <summary>How far from the midpoint of an anchor pair to look for the door.</summary>
        private const int DoorSearch = 3;

        public static void Initialize()
        {
            HealthCheck.Register("Nav.Doors", BuildHealthResult);

            // Once per boot, after the world has settled. Late enough that the population fill and
            // the spawners are done; early enough that the first [CoreSmoke of a session already
            // has a real answer rather than "not run this boot".
            EventSink.ServerStarted += () => Timer.DelayCall(TimeSpan.FromSeconds(20.0), () => Run());
        }

        public static HealthResult BuildHealthResult()
        {
            if (_last == null)
            {
                return HealthResult.Ok("not run this boot (runs at startup and with [BotSmoke)");
            }

            return _last;
        }

        /// <summary>
        /// Plan a route through a real closed door for a bot and for a plain player, then walk the
        /// bot's first step into the door.
        ///
        /// Synchronous, and everything it creates is deleted in the finally - an accountless
        /// PlayerMobile left standing would be written to the save like any other mobile.
        /// </summary>
        public static HealthResult Run()
        {
            Map map = Map.Trammel;

            if (map == null)
            {
                return Store(HealthResult.Warn("Trammel is not loaded, so there is nothing to ask"));
            }

            BaseDoor door = null;
            Anchor anchor = null;

            for (int i = 0; i < Anchors.Length && door == null; i++)
            {
                door = FindDoor(map, Anchors[i]);

                if (door != null)
                {
                    anchor = Anchors[i];
                }
            }

            if (door == null)
            {
                // Warn rather than Fail, and NOT Ok: the check could not run, which is a different
                // fact from the contract holding. Nav.Actor reports its own "no sources" the same
                // way, for the same reason - a check that passes when it cannot see anything
                // teaches everybody to ignore it.
                return Store(HealthResult.Warn(String.Format(
                    "no closed, unlocked door found within {0} tiles of either anchor ({1}), so "
                    + "the door gate could not be exercised. Either the graph moved or the world "
                    + "has no doors - run [DoorGen if this is a fresh world.",
                    DoorSearch,
                    Describe(Anchors))));
            }

            PlayerBot bot = null;
            PlayerMobile player = null;
            bool openedIt = false;

            try
            {
                bot = new PlayerBot(BotClass.Warrior, BotSkillTier.Journeyman);

                player = new PlayerMobile
                {
                    Name = "Nav Door Probe Player",
                    Body = 0x190,
                    AccessLevel = AccessLevel.Player,
                    Blessed = true
                };

                var doorTile = new Point2D(door.X, door.Y);

                // ---- half one: the bot's route must plan through the door ----
                bot.MoveToWorld(anchor.Outside, map);

                var botPath = new MovementPath(bot, anchor.Inside);
                List<Point2D> botTiles = TilesOf(anchor.Outside, botPath);

                if (!botPath.Success)
                {
                    return Fail(String.Format(
                        "a bot could not route {0} at all ({1} -> {2}). MODIFICATIONS entry 6 is "
                        + "reverted, or the graph has moved off this doorway.",
                        anchor.Name,
                        anchor.Outside,
                        anchor.Inside));
                }

                if (!botTiles.Contains(doorTile))
                {
                    return Fail(String.Format(
                        "a bot routed {0} in {1} step(s) but AROUND the closed door at {2},{3} - "
                        + "so the pathfinder is not planning through it. That is MODIFICATIONS "
                        + "entry 6 reverted: FastAStarAlgorithm sets MoveImpl.AlwaysIgnoreDoors "
                        + "only for a BaseCreature unless the bot branch is there.",
                        anchor.Name,
                        botPath.Directions.Length,
                        door.X,
                        door.Y));
                }

                // ---- half two: a plain player's route must not ----
                //
                // THE HALF THAT CATCHES AN OVER-WIDENED PATCH. A gate widened to every
                // PlayerMobile would make this route succeed through the door, and nothing else in
                // the suite would notice.
                player.MoveToWorld(anchor.Outside, map);

                var playerPath = new MovementPath(player, anchor.Inside);
                List<Point2D> playerTiles = TilesOf(anchor.Outside, playerPath);

                if (playerPath.Success && playerTiles.Contains(doorTile))
                {
                    return Fail(String.Format(
                        "a plain PlayerMobile also routed through the closed door at {0},{1}. The "
                        + "gate has been widened past bots - BotPathPolicy.IgnoreDoors must answer "
                        + "null for anything that is not an IBotActor, or every player gets a "
                        + "route through doors they still have to open by hand.",
                        door.X,
                        door.Y));
                }

                // ---- the leak named in entry 6 ----
                if (MoveImpl.AlwaysIgnoreDoors)
                {
                    return Fail(
                        "MoveImpl.AlwaysIgnoreDoors is still set after the paths were built. It is "
                        + "one static bool read for EVERY mobile on the shard, so a leak here has "
                        + "the whole world walking through doors. FastAStarAlgorithm resets it "
                        + "after every GetSuccessors call (:102); something is setting it outside "
                        + "that loop.");
                }

                // ---- half three: the step meets the route ----
                //
                // The stand tile and the direction come from the ROUTE rather than from geometry,
                // so this walks the step the pathfinder actually planned.
                int index = botTiles.IndexOf(doorTile);

                if (index <= 0)
                {
                    return Fail(String.Format(
                        "the door tile {0},{1} is the route's own start tile, so there is no step "
                        + "onto it to walk. The anchor needs moving.",
                        door.X,
                        door.Y));
                }

                Point2D stand = botTiles[index - 1];
                Direction step = botPath.Directions[index - 1];

                bot.MoveToWorld(new Point3D(stand.X, stand.Y, ZAt(map, stand, anchor.Outside.Z)), map);

                // FACE IT FIRST, or the Move below is a TURN and not a step.
                //
                // Mobile.Move returns true for a turn without moving anything, which is the same
                // rule PlayerBot.Move's own comment leans on from the other side: by the time Move
                // returns FALSE the mobile is already facing d. A probe that skipped this read
                // "Move returned True, it is standing where it started, the door is still shut" -
                // a green engine reported as a broken one. The engine's own pathfinding walker
                // does exactly this, `from.Direction = d;` before `from.Move(d)`
                // (MovementPath.cs:152-155).
                bot.Direction = step;

                bool moved = bot.Move(step);
                openedIt = door.Open;

                if (!moved || bot.X != door.X || bot.Y != door.Y)
                {
                    return Fail(String.Format(
                        "the bot planned a route through the door at {0},{1} and then could not "
                        + "take the step onto it from {2},{3} (Move returned {4}, it is standing "
                        + "at {5},{6}, the door is {7}). The two halves of the door fix have come "
                        + "apart: PlayerBot.Move opens the tile ahead through DoorHelper, and that "
                        + "is what makes a planned route walkable.",
                        door.X,
                        door.Y,
                        stand.X,
                        stand.Y,
                        moved,
                        bot.X,
                        bot.Y,
                        door.Open ? "open" : "still shut"));
                }

                var detail = String.Format(
                    "{0}: a bot routes through the closed door at {1},{2} in {3} step(s) and opens "
                    + "it on the step, a plain PlayerMobile {4}",
                    anchor.Name,
                    door.X,
                    door.Y,
                    botPath.Directions.Length,
                    playerPath.Success ? "routes around it" : "cannot route at all");

                Log.Info("Nav door check - {0}", detail);

                return Store(HealthResult.Ok(detail));
            }
            catch (Exception ex)
            {
                Log.Error(ex, "The door contract probe faulted.");

                return Fail("the probe faulted: " + ex.Message);
            }
            finally
            {
                // Shut behind us. The check found it closed and every other instrument in the tree
                // - the arrival scatter, ResolveZ, the audit's door false positives - is written
                // against the state it was in.
                if (openedIt && door != null && !door.Deleted && door.Open)
                {
                    door.Open = false;
                }

                if (bot != null && !bot.Deleted)
                {
                    BotMovement.ReleaseMount(bot);
                    bot.Delete();
                }

                if (player != null && !player.Deleted)
                {
                    player.Delete();
                }
            }
        }

        /// <summary>
        /// A closed, unlocked door between an anchor's two tiles.
        ///
        /// LOCKED DOORS ARE REFUSED, and that is not fussiness. ServUO's AlwaysIgnoreDoors has no
        /// "unlocked only" notion, so a bot's route WILL plan through a locked door and then fail
        /// to open it - the known limit entry 6 records and the `locked-door` ledger cause counts.
        /// A check built on one would be asserting the bug.
        /// </summary>
        private static BaseDoor FindDoor(Map map, Anchor anchor)
        {
            var mid = new Point3D(
                (anchor.Outside.X + anchor.Inside.X) / 2,
                (anchor.Outside.Y + anchor.Inside.Y) / 2,
                anchor.Outside.Z);

            IPooledEnumerable<Item> items = map.GetItemsInRange(mid, DoorSearch);

            try
            {
                foreach (Item item in items)
                {
                    var door = item as BaseDoor;

                    if (door == null || door.Open || door.Locked || door.Deleted)
                    {
                        continue;
                    }

                    // Same floor as the anchor. An upper-storey door three tiles away horizontally
                    // is not the one this route goes through.
                    if (Math.Abs(door.Z - anchor.Outside.Z) > 16)
                    {
                        continue;
                    }

                    return door;
                }
            }
            finally
            {
                items.Free();
            }

            return null;
        }

        /// <summary>
        /// The tiles a route passes over, start included, by replaying its directions the way the
        /// walker does. MovementPath hands back directions, not tiles, and "does this route go
        /// through the door" is a question about tiles.
        /// </summary>
        private static List<Point2D> TilesOf(Point3D start, MovementPath path)
        {
            var tiles = new List<Point2D>();

            int x = start.X;
            int y = start.Y;

            tiles.Add(new Point2D(x, y));

            if (path == null || !path.Success)
            {
                return tiles;
            }

            for (int i = 0; i < path.Directions.Length; i++)
            {
                CalcMoves.Offset(path.Directions[i], ref x, ref y);
                tiles.Add(new Point2D(x, y));
            }

            return tiles;
        }

        /// <summary>
        /// A Z to stand the bot at. The route is planar - MovementPath returns directions - so the
        /// Z has to come from the map, with the anchor's own as the hint a doorway at an unusual
        /// storey needs.
        /// </summary>
        private static int ZAt(Map map, Point2D tile, int hint)
        {
            return map.CanFit(tile.X, tile.Y, hint, 16, false, false, true)
                ? hint
                : map.GetAverageZ(tile.X, tile.Y);
        }

        private static string Describe(Anchor[] anchors)
        {
            var names = new List<string>();

            for (int i = 0; i < anchors.Length; i++)
            {
                names.Add(anchors[i].Name);
            }

            return String.Join(", ", names.ToArray());
        }

        private static HealthResult Fail(string why)
        {
            Log.Error("Nav door check FAILED - {0}", why);

            return Store(HealthResult.Fail(why));
        }

        private static HealthResult Store(HealthResult result)
        {
            _last = result;

            return result;
        }
    }
}
