// Creating records: the click-by-click tools, and the form that finishes each one.
//
// A tool collects geometry on the canvas, then a modal asks for the fields the geometry cannot
// supply. Nothing is validated for real here - validate.js previews and the shard decides - but
// the pickers are populated from the shapes already loaded, so a valid choice is the easy one.
//
// WHAT A TOOL IS: a data record, not an object with methods. `kind` names one of six behaviours
// and the state machine for all six lives in app.js. Adding a tool is a table entry; adding a new
// KIND is a change in three places, which is the right amount of friction for the difference.
//
// The ModernUO original's `route` and `point-then-route` kinds are gone rather than ported. They
// collected free polylines, and there is nothing in this schema to write one to: an edge's line is
// its two endpoints and a route's is its waypoint list. Their replacements collect ids instead.
//
// NO FIELD CARRIES ITS OWN LIST OF VALUES. A field names a key in the vocabulary
// (js/vocab.js -> /api/vocabulary) and the control is filled from that when the form opens.
// Before this, half these fields were free text with an example value typed into the table -
// `value: 'shop'` for a destination type, `'mine or lumber'` in a label - which is a copy of the
// shard's vocabulary that nothing checks and nothing updates. uo-offline has the same fault more
// visibly: a checked-in spawn_types.json regenerated by hand, and a literal behaviour array in
// the page (map-editor/map.html:204).
//
// SELECT ONLY WHERE THE SHARD HAS A CLOSED SET. Route mode, edge kind, spawner kind - those are
// C# enums and a value outside them is a file the shard refuses. Destination type, every tag
// field and the site type are `combo`, because NavRecords.cs deliberately makes them free tokens
// ("uo-offline-server's flat enum conflated category and mechanism; ours is a free token
// deliberately", ValidateDestinations) and a control stricter than the file format would stop
// you authoring a type the shard would have accepted. uo-offline reached the same answer for the
// same reason - map.html:126 is an <input list>, not a <select>.
//
// FIELD KEYS:
//   options      a literal closed list - only for sets that are not the shard's to change
//   optionsFrom  a vocabulary key; renders a <select> unless `combo` is set
//   combo        typeable: an <input list> over a generated <datalist>
//   dependsOn    another field's key; refill this one whenever that one changes
//   help         one line under the label saying what the field decides
//   list         a static datalist id in index.html (the id pickers, filled by fillLists)

import * as vocab from './vocab.js';

const dom = {};

let resolveForm = null;

/**
 * Binds the modal.
 *
 * Called from boot() rather than run at module scope, which is how the ModernUO original did it -
 * and why importing that file threw until the modal existed. A module that must not be imported
 * before the DOM is ready stays a trap even once the DOM is ready.
 */
export function initTools() {
    dom.modal = document.getElementById('modal');
    dom.form = document.getElementById('modal-form');
    dom.title = document.getElementById('modal-title');
    dom.fields = document.getElementById('modal-fields');
    dom.error = document.getElementById('modal-error');
    dom.cancel = document.getElementById('modal-cancel');
    dom.ok = document.getElementById('modal-ok');

    dom.form.addEventListener('submit', (event) => {
        event.preventDefault();

        const values = {};

        for (const input of dom.fields.querySelectorAll('[name]')) {
            values[input.name] = input.type === 'checkbox' ? input.checked : input.value.trim();
        }

        for (const input of dom.fields.querySelectorAll('[required]')) {
            if (!values[input.name]) {
                dom.error.textContent = `${input.dataset.label} is required.`;
                input.focus();
                return;
            }
        }

        finish(values);
    });

    dom.cancel.addEventListener('click', () => finish(null));

    // Esc inside the modal must close the modal, not fall through to the canvas and deselect.
    dom.modal.addEventListener('keydown', (event) => {
        if (event.key === 'Escape') {
            event.stopPropagation();
            finish(null);
        }
    });
}

export const TOOLS = {
    waypoint: {
        layer: 'nav',
        label: 'Waypoint',
        kind: 'point',
        autoId: true,
        hint: 'Click where the waypoint goes. Esc cancels.',
        title: 'New waypoint',
        steps: ['Click where the waypoint goes'],
        fields: [
            {
                key: 'id', label: 'Id', required: true,
                help: 'Auto-generated from the enclosing zone, the way [NavMark does it. Editable'
                    + ' until the first save; after that it is what edges and routes name.'
            },
            {
                key: 'tags', label: 'Tags (space separated)', value: 'town road',
                optionsFrom: 'waypointTags', combo: true,
                help: 'The first tag names auto-generated ids around here. Cost tags also make a'
                    + ' hop cheaper or dearer to route through.'
            },
            { key: 'name', label: 'Display name (optional)' },
            {
                key: 'arrivalRange', label: 'Arrival range (0 = walker default)', value: '0',
                help: 'How close is close enough to count as arrived here.'
            }
        ]
    },

    /**
     * Ask the shard to walk a road between two points, and propose waypoints along it.
     *
     * Two clicks and no form, because it CREATES NOTHING BY ITSELF. What comes back is a draft
     * the author accepts, edits or throws away - the shard is answering "can a bot walk here and
     * where would the waypoints go", which is a question the browser cannot answer at all: it has
     * no map data, no movement rules, and no way to know that a bot opens a door and a flood does
     * not.
     */
    corridor: {
        layer: 'nav',
        label: 'Corridor',
        kind: 'point-chain',
        hint: 'Click where the road starts. Esc cancels.',
        hint2: 'Click via points to steer it, then the end. Enter or Finish routes it, Esc cancels.',
        title: 'New corridor',

        // The form is asked when the tool STARTS, before the first click - the only tool that
        // does. The name is what every waypoint the road mints is called, so it has to exist
        // before there is anything to name; and unlike the Site tool's form, which needs the
        // centre tile to auto-generate an id from, nothing here depends on the geometry.
        formAtStart: true,

        // Named steps for the whole tool, matching README's "Authoring a road" walkthrough so the
        // two cannot say different things.
        //
        // Two, not three: the routing itself is not a step you do anything during, and it already
        // narrates itself in the status line, leg by leg, because it is slow enough to need to.
        steps: [
            'Click where the road starts - on an existing waypoint to join the graph there',
            'Click via points to steer it, then the end. Enter routes it'
        ],
        fields: [
            {
                key: 'name', label: 'Corridor name', required: true,
                help: 'Names every waypoint the road mints: <name>-WP-0001 upward in walk order,'
                    + ' so the road reads as one set in the filter and in a navigation.json diff.'
            },
            {
                key: 'tags', label: 'Tags', value: 'road',
                optionsFrom: 'waypointTags', combo: true,
                help: 'Carried by both the waypoints and the edges between them.'
            }
        ]
    },

    /**
     * A work site is three records, and authoring them separately is how one gets forgotten.
     *
     * A mine or a wood is a destination (where bots are sent), a zone (the ground they may work
     * and shuffle within) and a set of arrival tiles (where they stand). Miss the zone and
     * GathererBehavior has no work area and walks the bot away; miss the arrivals and it has
     * nowhere to stand. The shard is asked for the harvest reach under each arrival as it is
     * placed, because until something with the map in front of it answers, an arrival tile is a
     * guess - and a guess is what once put a mine on grass.
     */
    site: {
        layer: 'nav-destinations',
        label: 'Work site',
        kind: 'site',
        autoId: true,
        hint: 'Click where the centre of the site goes. Esc cancels.',
        hint2: 'Drag out the zone the bots may work inside. Esc cancels.',
        hint3: 'Asking the shard where a bot could stand...',
        title: 'New work site',

        // Its form opens after the FIRST CLICK rather than at the start, because the auto id is
        // generated from the zone the centre tile lands in - and because the type it asks for
        // decides which harvest definition the sweep two steps later measures against. See
        // askForSite in app.js.
        steps: [
            'Click the centre of the face',
            'Drag out the zone the bots may work inside - where they wander, not where they stand',
            'Take the tiles worth standing on, then Enter'
        ],
        fields: [
            {
                key: 'id', label: 'Id', required: true,
                help: 'Auto-generated from the enclosing zone. The zone and the arrival points are'
                    + ' named from it, so a site reads as a set: brit-mine-west, -west-face.'
            },
            {
                key: 'name', label: 'Display name', required: true,
                help: "What a bot's status line calls it."
            },
            {
                key: 'type', label: 'Type', required: true, value: 'mine',
                optionsFrom: 'siteTypes', combo: true,
                help: 'Decides which harvest definition the sweep measures against - a mine floors'
                    + ' at 5 reachable tiles, a wood at 3 - and which zone tag GathererBehavior'
                    + ' looks for at the bot’s feet.'
            },
            {
                key: 'tags', label: 'Tags', value: 'wilderness',
                optionsFrom: 'destinationTags', combo: true,
                help: 'On the destination. The zone minted with it always carries'
                    + ' "<type> wilderness work" as well, whatever is typed here.'
            },
            {
                key: 'waypoints', label: 'Approach waypoints', list: 'waypoint-list',
                help: 'Where a bot walks in from. Every arrival has to sit within the hop cap of'
                    + ' one of these or nothing can route to the site.'
            }
        ]
    },

    destination: {
        layer: 'nav-destinations',
        label: 'Destination',
        kind: 'point',
        autoId: true,
        hint: 'Click where the destination is. Esc cancels.',
        title: 'New destination',
        steps: ['Click where the destination is'],
        fields: [
            { key: 'id', label: 'Id', required: true },
            { key: 'name', label: 'Display name', required: true },
            {
                key: 'type', label: 'Type', required: true,
                optionsFrom: 'destinationTypes', combo: true,
                help: 'What bots come here for. Typeable: the shard treats a type as a free token'
                    + ' and bots.json weights the ones it has an opinion about.'
            },
            {
                key: 'tags', label: 'Tags', optionsFrom: 'destinationTags', combo: true,
                help: "Multiply the class weights on top of the type's. A town tag also makes this"
                    + " a home-town destination for bots born there."
            },
            {
                key: 'waypoints', label: 'Approach waypoints', list: 'waypoint-list',
                help: 'Where a bot walks in from, space separated.'
            }
        ]
    },

    arrival: {
        layer: 'nav-arrivals',
        label: 'Arrival',
        // Two phases: whose arrival it is, then where. An arrival with no destination is not a
        // thing the schema can express, so the destination is collected first rather than typed.
        kind: 'owner-then-point',
        picks: 'nav-destinations',
        hint: 'Click the destination this arrival belongs to. Esc cancels.',
        hint2: 'Now click a tile someone could stand on. Esc cancels.',
        title: 'New arrival point',
        steps: ['Click the destination this arrival belongs to', 'Click a tile someone can stand on'],
        fields: [
            {
                key: 'exclusive', label: 'Exclusive - a guard post, nobody else stands here',
                checkbox: true,
                help: 'One occupant at a time. Everyone else queues for another arrival.'
            },
            {
                key: 'exact', label: 'Exact - do not scatter', checkbox: true,
                help: 'A shop spot is normally scattered by Custom.NavArrivalScatter so a crowd'
                    + ' does not stack. This pins it to the tile.'
            },
            {
                key: 'range', label: 'Arrival range (0 = the tile)', value: '0',
                help: 'How far around the tile still counts as arrived. The forge arrivals author'
                    + ' 2; banks, shops and guard posts keep the tile.'
            },
            {
                key: 'waypoints', label: 'Approach waypoints', list: 'waypoint-list',
                help: 'Where a bot walks in from. Blank inherits the destination’s.'
            }
        ]
    },

    edge: {
        layer: 'nav-edges',
        label: 'Edge',
        // No form at all: an edge is entirely its two ends, and a modal asking nothing would be
        // two clicks of ceremony for no information.
        kind: 'pair',
        picks: 'nav',
        hint: 'Click the first waypoint. Esc cancels.',
        hint2: 'Now click the second. Esc cancels.',
        title: 'New edge',
        steps: ['Click the first waypoint', 'Click the second'],
        fields: []
    },

    route: {
        layer: 'nav-routes',
        label: 'Route',
        kind: 'chain',
        picks: 'nav',
        min: 2,
        hint: 'Click each waypoint in order. Enter finishes, Esc cancels.',
        title: 'New route',
        steps: ['Click each waypoint in order, then Enter'],
        fields: [
            { key: 'id', label: 'Id', required: true },
            {
                // A select, not a combo: NavRouteMode is a C# enum and a fourth value is a file
                // the shard refuses to load. The list comes from the shard all the same.
                key: 'mode', label: 'Mode', optionsFrom: 'routeModes',
                help: 'cycle wraps back to the first waypoint, oneway stops at the last,'
                    + ' pingpong runs to the end and back forever.'
            }
        ]
    },

    navzone: {
        layer: 'nav-zones',
        label: 'Nav zone',
        kind: 'rect',
        autoId: true,
        hint: 'Drag a rectangle for the zone. Esc cancels.',
        title: 'New nav zone',
        steps: ['Drag a rectangle for the zone'],
        fields: [
            { key: 'id', label: 'Id', required: true },
            {
                key: 'tags', label: 'Tags', value: 'town',
                optionsFrom: 'zoneTags', combo: true,
                help: 'The first tag names auto-generated ids inside this zone. A work zone also'
                    + ' needs its site type here for GathererBehavior to find it.'
            }
        ]
    },

    /**
     * Adopt a region of the uo-offline reference.
     *
     * `adopt-rect` rather than `rect`: it creates no record of its own. The rectangle is a
     * QUESTION asked of the shard - which of somebody else's roads are in here, and can they be
     * walked - and the answer comes back as a proposal to accept or discard.
     */
    adopt: {
        layer: 'reference',
        label: 'Adopt region',
        kind: 'adopt-rect',
        hint: 'Drag a box over the reference roads to adopt. Esc cancels.',
        title: 'Adopt region',
        fields: []
    },

    restricted: {
        layer: 'restricted',
        label: 'Restricted zone',
        kind: 'rect',
        hint: 'Drag a rectangle for the restricted zone. Esc cancels.',
        title: 'New restricted zone',
        steps: ['Drag a rectangle for the restricted zone'],
        fields: [{
            key: 'name', label: 'Name', required: true,
            help: 'Shown in the countdown gump a player gets for standing in it.'
        }]
    },

    /**
     * Rebuilt on uo-offline's spawn form (map-editor/map.html:118-133, JS at :1101-1141): the
     * kind first, then a type list filtered by it, then count, range and the respawn window.
     *
     * KIND FIRST BECAUSE THE TYPE LIST IS MEANINGLESS WITHOUT IT. 1,400 creature names in one
     * combo is not a list anybody reads; filtered to a kind it is something you can scan.
     *
     * The counts on the kind labels are ours rather than theirs, and they are there because the
     * split is derived: the shard says which types exist and the bridge says which folder each
     * was written in. A scan that found nothing gives an empty type list, and an empty dropdown
     * is indistinguishable from one still loading. `Monster (0)` is not.
     */
    spawner: {
        layer: 'spawners',
        label: 'Spawner',
        kind: 'point',
        autoId: true,
        hint: 'Click where the spawner goes. Esc cancels.',
        title: 'New GG spawner',
        steps: ['Click where the spawner goes'],
        fields: [
            {
                key: 'kind', label: 'Kind',
                optionsFrom: (v) => v.spawnKinds().map((entry) => ({
                    value: entry.key, label: `${entry.label} (${entry.count})`
                })),
                help: 'Filters the type list below. The two bot kinds uo-offline offers - fixed'
                    + ' role and lifecycle seed - come with the Population session; this shard has'
                    + ' no bot spawner yet.'
            },
            {
                key: 'Objects2', label: 'Type', required: true,
                dependsOn: 'kind', combo: true,
                optionsFrom: (v, values) => v.spawnTypes(values.kind || 'Monster'),
                help: 'What it spawns. Typeable, because even one kind is hundreds of entries -'
                    + ' the list is every type the shard actually loaded with a constructor a'
                    + ' spawner can call.'
            },
            {
                // GG_ is not decoration: [XmlLoad and [XmlUnLoad filter on it with an ordinal
                // StartsWith, which is what makes this shard's spawners addressable as a set. It
                // is applied by build.js rather than typed - a prefix everybody has to remember
                // is a prefix somebody will forget, and the spawner that forgets it is invisible
                // to [GG_Reimport for ever.
                key: 'Name', label: 'Name', required: true,
                help: 'GG_ is added automatically. Type the rest.'
            },
            {
                key: 'file', label: 'File', required: true,
                optionsFrom: 'spawnFiles', combo: true,
                help: 'Which Spawns/Custom file it lands in. Saving reloads that one file, not'
                    + ' every GG spawner. Type a new spawn:<facet>/GG_Name.xml to start one.'
            },
            {
                key: 'MaxCount', label: 'Count', value: '1',
                help: 'How many stand here at once.'
            },
            {
                key: 'Range', label: 'Home range', value: '0',
                help: 'How far from this tile they may wander. 0 pins them to it.'
            },
            {
                key: 'MinDelay', label: 'Respawn min (minutes)', value: '5',
                help: 'The soonest a killed spawn comes back.'
            },
            {
                key: 'MaxDelay', label: 'Respawn max (minutes)', value: '10',
                help: 'The latest. The actual delay is rolled between the two.'
            }
        ]
    }
};

function finish(values) {
    dom.modal.hidden = true;

    const resolve = resolveForm;

    resolveForm = null;
    resolve?.(values);
}

/**
 * Opens the modal and resolves with the field values, or null if cancelled.
 *
 * Takes anything with a title and a list of fields, so it serves both the create tools and one-off
 * prompts like "go to coordinate" without a second dialog implementation.
 */
export function askFor(tool, defaults) {
    dom.title.textContent = tool.title;
    dom.ok.textContent = tool.submit || 'Create';
    dom.error.textContent = '';
    dom.fields.innerHTML = '';

    // Fields that another field drives, so a change can refill them without re-rendering the form
    // and losing what has already been typed into it.
    const dependents = [];

    for (const field of tool.fields) {
        const label = document.createElement('label');
        const caption = document.createElement('span');

        caption.textContent = field.label;

        let input;

        if (field.options || (field.optionsFrom && !field.combo)) {
            input = document.createElement('select');
            fillSelect(input, optionsOf(field, defaults));
        } else {
            input = document.createElement('input');
            input.type = field.checkbox ? 'checkbox' : 'text';
            input.autocomplete = 'off';

            if (field.list) {
                input.setAttribute('list', field.list);
            }

            // A combo is an <input list> over a datalist minted for this field. Its own element
            // rather than one of the shared ones in index.html, because a dependent list changes
            // as another field changes and a shared datalist would leak that into every form
            // using it.
            if (field.optionsFrom) {
                const datalist = document.createElement('datalist');

                datalist.id = `modal-list-${field.key}`;
                input.setAttribute('list', datalist.id);
                fillDatalist(datalist, optionsOf(field, defaults));
                label.append(datalist);
            }
        }

        input.name = field.key;
        input.dataset.label = field.label;

        const preset = defaults && field.key in defaults ? defaults[field.key] : field.value;

        if (preset !== undefined && preset !== null) {
            if (field.checkbox) {
                input.checked = preset === true || preset === 'true';
            } else {
                input.value = String(preset);
            }
        }

        if (field.required) {
            input.required = true;
        }

        label.append(caption, input);

        // The one line saying what the field decides. Under the control rather than in the label,
        // so the label stays scannable and the explanation is there when you stop on it.
        if (field.help) {
            const help = document.createElement('small');

            help.className = 'field-help';
            help.textContent = field.help;
            label.append(help);
        }

        dom.fields.append(label);

        if (field.dependsOn) {
            dependents.push(field);
        }
    }

    // Wired after every control exists, because a dependent may be declared before the field it
    // depends on.
    for (const field of dependents) {
        const driver = dom.fields.querySelector(`[name="${field.dependsOn}"]`);
        const target = dom.fields.querySelector(`[name="${field.key}"]`);

        if (!driver || !target) {
            continue;
        }

        driver.addEventListener('change', () => {
            const values = optionsOf(field, { [field.dependsOn]: driver.value });

            if (target.tagName === 'SELECT') {
                fillSelect(target, values);
                return;
            }

            fillDatalist(document.getElementById(`modal-list-${field.key}`), values);

            // A type from the previous kind is not a type of this one. Cleared rather than left,
            // because a stale value that no longer appears in the list is exactly the thing that
            // gets saved by accident.
            const plain = values.map((v) => (typeof v === 'string' ? v : v.value));

            if (target.value && !plain.includes(target.value)) {
                target.value = '';
            }
        });
    }

    dom.modal.hidden = false;
    dom.fields.querySelector('[name]')?.focus();

    return new Promise((resolve) => {
        resolveForm = resolve;
    });
}

/**
 * The values a field offers right now.
 *
 * `filter` lets a field narrow the vocabulary by another field's current value - the spawner's
 * type list is the vocabulary's `spawnTypes` for whichever kind is selected.
 */
function optionsOf(field, values) {
    if (field.options) {
        return field.options.slice();
    }

    if (!field.optionsFrom) {
        return [];
    }

    if (typeof field.optionsFrom === 'function') {
        return field.optionsFrom(vocab, values || {});
    }

    return vocab.optionsFor(field.optionsFrom);
}

function fillSelect(select, values) {
    select.innerHTML = '';

    for (const value of values) {
        const option = document.createElement('option');

        // A value may be a bare string or a {value, label} pair - the spawner's kinds carry their
        // type count in the label, which is how an empty bucket is visible in the form rather
        // than looking like a list that has not loaded.
        option.value = typeof value === 'string' ? value : value.value;
        option.textContent = typeof value === 'string' ? value : value.label;
        select.append(option);
    }
}

function fillDatalist(datalist, values) {
    if (!datalist) {
        return;
    }

    datalist.innerHTML = '';

    for (const value of values) {
        const option = document.createElement('option');

        option.value = typeof value === 'string' ? value : value.value;
        datalist.append(option);
    }
}

export function showModalError(message) {
    dom.error.textContent = message;
}

/** Fills the id pickers from the shapes already loaded. */
export function fillLists(shapes) {
    const of = (prefix) => shapes
        .filter((shape) => shape.id.startsWith(prefix + ':'))
        .map((shape) => shape.id.slice(prefix.length + 1));

    const waypoints = of('wp');
    const destinations = of('dest');

    fill('waypoint-list', waypoints);
    fill('destination-list', destinations);
    fill('route-list', of('route'));

    // Anything a daily-life field may name: Nav.TryRoute takes either, and so does a shop or home.
    fill('navid-list', [...destinations, ...waypoints]);

    // The spawn-file and creature lists used to be derived here, from the spawn files loaded and
    // from every <Objects2> entry already on the map. Both now come from the vocabulary instead
    // (js/vocab.js): the files from the directory rather than from whichever ones the viewport
    // happened to load, and the types from what the shard actually has a constructable class for
    // rather than from what is already spawning - which could never suggest a type nobody had
    // used yet, and could happily suggest one that no longer compiles.
}

function fill(id, values) {
    const list = document.getElementById(id);

    if (!list) {
        return;
    }

    list.innerHTML = '';

    for (const value of values) {
        const option = document.createElement('option');

        option.value = value;
        list.append(option);
    }
}
