using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;

using Server.Commands;
using Server.Mobiles;

namespace Server.Custom
{
    /// <summary>
    /// What the shard actually loaded, to Data/Live/vocabulary.json, so the editor's forms can be
    /// dropdowns instead of free text.
    ///
    /// THE PROBLEM THIS SOLVES is a hand-kept list. Every create form in the editor used to ask
    /// for a destination type, a tag or a creature name as free text, with an example value typed
    /// into tools.js - which is a copy of the shard's vocabulary that nothing checks and nothing
    /// updates. uo-offline made the same mistake more visibly: its spawn types are a checked-in
    /// spawn_types.json regenerated by hand from a Python source-scanner
    /// (map-editor/gen_spawn_types.py) and its bot behaviours are a literal array in the page
    /// (map-editor/map.html:204). Both drift, and neither says when.
    ///
    /// So the lists are fetched, and this is the half only the shard can answer.
    ///
    /// WHAT IS HERE AND WHAT IS NOT. This reports what cannot be read off a file in the repo:
    /// the loaded type set, and the C# enums. The rest of the vocabulary - which destination
    /// types and tags are in use, which the bot layer weights, which spawn files exist - the
    /// bridge derives from navigation.json, bots.json and the Spawns/Custom directory, because it
    /// already reads all three and doing it there means the editor still opens its forms with the
    /// shard down.
    ///
    /// THE MONSTER/NPC SPLIT IS DELIBERATELY ABSENT. ServUO exposes no source folder at runtime,
    /// and Scripts/Mobiles/Normal holds Alligator next to Balron, so nothing here can tell a
    /// townsfolk from a dragon without instantiating it. That split is a fact about the repo, and
    /// the bridge scans Scripts/Mobiles for it. What this can answer exactly is the vendor
    /// question, from the type chain - so vendors come back as their own list and the bridge's
    /// folder scan never gets a say in it.
    ///
    /// ON REQUEST, NOT ON A TIMER. Reflecting over every loaded type is not free and the answer
    /// only changes when Scripts.dll does, which means a rebuild, which means a restart. The
    /// bridge asks once when its cached copy is missing or older than the assembly.
    /// </summary>
    public static class VocabularySnapshot
    {
        private static readonly CustomLogger Log = CustomLogger.For("Bridge");

        public const string OutputPath = "Data/Live/vocabulary.json";

        private static long _sequence;
        private static DateTime? _lastUtc;
        private static int _lastCreatures;
        private static int _lastVendors;
        private static string _lastError;

        public static void Initialize()
        {
            CommandSystem.Register("Vocabulary", AccessLevel.Administrator, Vocabulary_OnCommand);
            HealthCheck.Register("Bridge.Vocabulary", BuildHealthResult);
        }

        [Usage("Vocabulary")]
        [Description("Writes the editor's vocabulary snapshot: loaded creature types and the shard's enums.")]
        private static void Vocabulary_OnCommand(CommandEventArgs e)
        {
            string message;

            e.Mobile.SendMessage(TryWrite(out message) ? 0x40 : 0x22, message);
        }

        /// <summary>
        /// Writes the snapshot. Returns false with a reason rather than throwing, so the request
        /// token and the command can both say what went wrong.
        /// </summary>
        public static bool TryWrite(out string message)
        {
            try
            {
                _sequence++;

                List<string> creatures;
                List<string> vendors;

                CollectTypes(out creatures, out vendors);

                string error;

                if (!AtomicFile.Write(OutputPath, Build(creatures, vendors), out error))
                {
                    _lastError = error;
                    message = "could not write " + OutputPath + ": " + error;
                    Log.Error("Could not write {0}: {1}", OutputPath, error);
                    return false;
                }

                _lastError = null;
                _lastUtc = DateTime.UtcNow;
                _lastCreatures = creatures.Count;
                _lastVendors = vendors.Count;

                message = String.Format(
                    "{0} creature type(s) and {1} vendor type(s) written to {2}",
                    creatures.Count, vendors.Count, OutputPath);

                Log.Info(message);
                return true;
            }
            catch (Exception ex)
            {
                _lastError = ex.Message;
                message = "vocabulary snapshot failed: " + ex.Message;
                Log.Error(ex, "Vocabulary snapshot failed.");
                return false;
            }
        }

        /// <summary>
        /// Every type a spawner could name, split into the one bucket reflection can decide.
        ///
        /// The filter is exactly what XmlSpawner needs to spawn one: a concrete BaseCreature
        /// subclass with a public parameterless constructor. XmlSpawner2.cs:11346 calls
        /// Activator.CreateInstance(type) with no arguments for a bare type name, so a type
        /// without that constructor is one the editor would let you author and the shard would
        /// then refuse - which is the whole class of mistake this list exists to prevent.
        ///
        /// [Constructable] is deliberately NOT the filter. It gates the [Add command, not the
        /// spawner, and requiring it here would hide types that spawn perfectly well.
        /// </summary>
        private static void CollectTypes(out List<string> creatures, out List<string> vendors)
        {
            creatures = new List<string>(1024);
            vendors = new List<string>(256);

            var seen = new HashSet<string>(StringComparer.Ordinal);

            Type creature = typeof(BaseCreature);
            Type vendor = typeof(BaseVendor);

            foreach (Assembly assembly in Assemblies())
            {
                Type[] types;

                try
                {
                    types = ScriptCompiler.GetTypeCache(assembly).Types;
                }
                catch (Exception ex)
                {
                    // One unloadable assembly must not cost the whole list. Named rather than
                    // swallowed, because a missing bucket looks like a scan that found nothing.
                    Log.Warn("Could not read the type cache for {0}: {1}",
                        assembly == null ? "(null)" : assembly.GetName().Name, ex.Message);
                    continue;
                }

                if (types == null)
                {
                    continue;
                }

                for (int i = 0; i < types.Length; i++)
                {
                    Type type = types[i];

                    if (type == null || type.IsAbstract || !creature.IsAssignableFrom(type))
                    {
                        continue;
                    }

                    if (type.GetConstructor(Type.EmptyTypes) == null)
                    {
                        continue;
                    }

                    // A name, not a full name: <Objects2> and the [Add command both take the short
                    // name, and ScriptCompiler.FindTypeByName is what resolves it back.
                    if (!seen.Add(type.Name))
                    {
                        continue;
                    }

                    if (vendor.IsAssignableFrom(type))
                    {
                        vendors.Add(type.Name);
                    }
                    else
                    {
                        creatures.Add(type.Name);
                    }
                }
            }

            creatures.Sort(StringComparer.Ordinal);
            vendors.Sort(StringComparer.Ordinal);
        }

        /// <summary>
        /// Scripts.dll and the core, which is where every loaded type lives.
        ///
        /// Core.Assembly is added by hand because ScriptCompiler.Assemblies does not contain it -
        /// every lookup in ScriptCompiler falls back to it separately (see FindTypeByName), and a
        /// scan that copied only the array would silently miss anything defined in Server/.
        /// </summary>
        private static IEnumerable<Assembly> Assemblies()
        {
            Assembly[] scripts = ScriptCompiler.Assemblies;

            if (scripts != null)
            {
                for (int i = 0; i < scripts.Length; i++)
                {
                    if (scripts[i] != null)
                    {
                        yield return scripts[i];
                    }
                }
            }

            if (Core.Assembly != null)
            {
                yield return Core.Assembly;
            }
        }

        private static string Build(List<string> creatures, List<string> vendors)
        {
            var builder = new StringBuilder(64 * 1024);

            builder.Append("{\n");
            builder.Append("  \"sequence\": ").Append(_sequence).Append(",\n");
            builder.Append("  \"utc\": ").Append(Json.Quote(DateTime.UtcNow.ToString("o"))).Append(",\n");

            AppendArray(builder, "creatures", creatures);
            AppendArray(builder, "vendors", vendors);
            AppendArray(builder, "facets", Facets());

            // The gatherer site types, from the one place that decides which they are. The Site
            // tool's dropdown is these and nothing else: a type here that GathererBehavior does
            // not recognise gives a site nobody works.
            AppendArray(builder, "siteTypes", new List<string>(BotWorkSites.GathererSiteTypes));

            AppendArray(builder, "botClasses", EnumNames(typeof(BotClass), false));
            AppendArray(builder, "botTiers", EnumNames(typeof(BotSkillTier), false));
            AppendArray(builder, "crafterTypes", EnumNames(typeof(CrafterType), false));

            // The behaviours a bot spawner may seed, from the registry rather than from an enum,
            // because there is no enum: "the state IS the behaviour name" (BotBehaviors.cs:9-12).
            // This is the one dropdown in the editor whose values are C# CLASS NAMES the shard
            // resolves by string, so a stale list here is a spawner that silently makes an Idle
            // bot - which looks exactly like a spawner that works.
            AppendArray(builder, "botBehaviors", new List<string>(BotBehaviors.Names()));

            // Fixture or session. An enum precisely so this line can exist.
            AppendArray(builder, "botRoles", EnumNames(typeof(BotRole), false));

            // Lowercased, because that is how they are spelled in navigation.json: NavEdge.Kind
            // compares KindName against "gate" and NavRoute parses "oneway", so an editor offering
            // "OneWay" would be offering a value the file has never held.
            AppendArray(builder, "edgeKinds", EnumNames(typeof(NavEdgeKind), true));
            AppendArray(builder, "routeModes", EnumNames(typeof(NavRouteMode), true));

            // Legacy enum members are reported, not hidden, and flagged instead. BotClass.Crafter
            // is no longer rolled but existing bots still carry it, so a panel that could not name
            // it would show a blank where a class should be.
            builder.Append("  \"legacyBotClasses\": [")
                .Append(Json.Quote(BotClass.Crafter.ToString()))
                .Append("]\n");

            builder.Append("}\n");

            return builder.ToString();
        }

        private static List<string> Facets()
        {
            var names = new List<string>();

            foreach (Map map in Map.AllMaps)
            {
                if (map != null && map != Map.Internal)
                {
                    names.Add(map.Name);
                }
            }

            return names;
        }

        private static List<string> EnumNames(Type type, bool lowercase)
        {
            string[] names = Enum.GetNames(type);
            var result = new List<string>(names.Length);

            for (int i = 0; i < names.Length; i++)
            {
                result.Add(lowercase ? names[i].ToLowerInvariant() : names[i]);
            }

            return result;
        }

        private static void AppendArray(StringBuilder builder, string key, List<string> values)
        {
            builder.Append("  ").Append(Json.Quote(key)).Append(": [");

            for (int i = 0; i < values.Count; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(Json.Quote(values[i]));
            }

            builder.Append("],\n");
        }

        private static HealthResult BuildHealthResult()
        {
            if (_lastError != null)
            {
                return HealthResult.Fail("last write failed: " + _lastError);
            }

            if (_lastUtc == null)
            {
                return HealthResult.Ok("not written this run");
            }

            return HealthResult.Ok(String.Format(
                "{0} creature and {1} vendor type(s), written {2:u}",
                _lastCreatures, _lastVendors, _lastUtc.Value));
        }
    }
}
